# Generated by Django 4.2.27 on 2026-01-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Course & Exam Setting', 'verbose_name_plural': 'Course Management'},
        ),
        migrations.AddField(
            model_name='exam',
            name='active_until',
            field=models.DateTimeField(blank=True, help_text='Set the time when this exam should automatically stop being available.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('QUIZ', 'Quiz'), ('MID_SEM', 'Mid Semester'), ('EXAMS', 'Final Exams')], default='EXAMS', max_length=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='course_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(help_text='Enter 1, 2, 3, or 4'),
        ),
    ]
