# Generated by Django 4.2.27 on 2026-01-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_exam_options_exam_active_until_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='cheat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='active_until',
            field=models.DateTimeField(blank=True, help_text='Set the time when this exam should automatically stop.', null=True),
        ),
    ]
